remote_theme: vaibhavvikas/jekyll-theme-minimalistic
hide_project_page: true
github.is_user_page: false
hide_project_footer: true
title: 
description: 
navigation:
  - name: Readme
    link: ./index.html
  - name: אני מאמין באלוהים
    link: ./hbrw.html
